### ISSUE TITLE
Rangy initialisation fails when loaded in iframe on firefox

### ISSUE THREAD

**Issue by timdown** [timdown/rangy#138]
_From [wich...@wiggy.net](https://code.google.com/u/114586170066834814174/) on December 05, 2012 16:41:31_

I am loading rangy 1.2.3 in an iframe. When doing this on firefox 16 I get an initialisation error:

rangy-core.js (line 169) Init listener threw an exception. Continuing.
rangy-core.js (line 42) TypeError: o is null
  return typeof o[p] != UNDEFINED

That leaves me with a partially configured rangy object: methods such as getSelection are missing.

_Original issue: http://code.google.com/p/rangy/issues/detail?id=138_

**Comment by shardator** [comment]
Guess no fix for this yet...

**Comment by jefftaggart** [comment]
This issue still occurs if the iframe is within a element with style `display: none`.
