### ISSUE TITLE
Overlapping highlights not handled correctly

### ISSUE THREAD

**Issue by timdown** [timdown/rangy#168]
_From [simone.p...@gmail.com](https://code.google.com/u/108410088978618107804/) on May 31, 2013 11:50:28_

What steps will reproduce the problem? 1. Go to the highlighter demo
2. Highlight a selection
3. Highlight a selection that overlaps the one you highlighted before
4. Remove one of the two highlights What is the expected output? What do you see instead? The remaining highlight should be visible, it is deleted instead. Also the highlighter.highlights datastructure is now inconsistent.

_Original issue: http://code.google.com/p/rangy/issues/detail?id=168_

**Comment by timdown** [comment]
The merging of overlapping highlights is by design. I don't think there is now a problem with the state of  `highlighter.highlights`.

**Comment by pavneet9** [comment]
I am adding additional information to the class attrbute and when the highlights are overlapped i get two sets of data.
IS there a way for you to retain both the spans when the highlights are overlapped
