### ISSUE TITLE
rangy.getSelection().isCollapsed out of sync

### ISSUE THREAD

**Issue by timdown** [timdown/rangy#175]
_From [ben.get...@gmail.com](https://code.google.com/u/110649361582839499766/) on July 15, 2013 02:56:33_

What steps will reproduce the problem? 1. Make a selection on a page
2. Click anywhere on the selection (this ends up clearing the selection)

It may help to put a listener on the mouseup event on the document to print out the Selection. What is the expected output? What do you see instead? rangy.getSelection().isCollapsed == false
rangy.getSelection().nativeSelection.isCollapsed == true

I'm expecting isCollapsed to be `true` for the Rangy Selection (since nothing's selected on the page). What version of the product are you using? On what operating system? 1.3alpha.772
Windows Vista SP2
Chrome latest; Firefox latest Please provide any additional information below. Behavior is as expected when you click outside of the selection. It's just when you click _on_ the selection when clearing it.

_Original issue: http://code.google.com/p/rangy/issues/detail?id=175_

**Comment by githubajay1mishra** [comment]
Tim is right about the fact there is brief delay after releasing the mouse button on an existing selection. Issue: We wanted to show a menu option if user selected some text. We were using the rangy api to getSelection in mouseup event  but the rangy selection was out of sync when user clicked inside selected text.  
Fix: After adding a timeout  in the mouseup handler and then asking rangy.getSelection returned the correct value that matched browser selection.
It would have been nice if rangy gave an event whenever it detected a selection change. This would eliminate to wait for certain timeout and then ask rangy if its selection has changed.
