### ISSUE TITLE
CSSClassApplier crash in Safari & Firefox with range encompassing custom NS elements

### ISSUE THREAD

**Issue by timdown** [timdown/rangy#178]
_From [philip.p...@gmail.com](https://code.google.com/u/113469898388912448400/) on July 29, 2013 03:39:32_

In my quest to find exceedingly strange ways to use CSSClassApplier, I discovered the following steps can produce a crash in Safari & Firefox on OSX (not Chrome though...). If step #3 isn't supported, feel free to let me know and I'll see what I can do to work around it. What steps will reproduce the problem? (See attached html file)
1. Create a text node within a div container
2. Highlight the region
3. Append new custom elements within the tail end of the region (Is this step a "user error" by me? Is Rangy expected to play nice if I'm doing this to the DOM behind it?)
4. Re-apply the highlight to entire div container again. The apply command will crash at this point with the following error in firefox:
[12:26:06.837] TypeError: className is undefined @ http://rangy.googlecode.com/svn/trunk/dev/uncompressed/rangy-cssclassapplier.js:56 What is the expected output? What do you see instead? Hopefully it wouldn't crash What version of the product are you using? On what operating system? Reproducible in current uncompressed output in trunk. Also reproducible against compiled source output as of r790 .

Workarounds:
One possible workaround is to add a null check on line 56, changing the content of "sortClassName" to:
function sortClassName(className) {
    return className ? className.split(/\s+/).sort().join(" ") : "";
}

_Original issue: http://code.google.com/p/rangy/issues/detail?id=178_

**Comment by timdown** [comment]
Hi. I've made a change (not yet committed) that allows the class applier to work with elements with non-HTML namespaces, such as `<svg>` elements and elements with custom namespace elements. This changes the behaviour so that these elements are no longer ignored. Would this be a problem for you?

**Comment by peitschie** [comment]
Your solution sounds preferable to me.

As you guessed, I simply took the easiest route to non-throwing. In my specific use-case, I was indifferent to whether the class was applied to the svg elements or not.

Thanks for your work!
