### ISSUE TITLE
el.currentStyle is null or undefined on ie8 for node: <param>

### ISSUE THREAD

**Issue by jgabios** [timdown/rangy#259]
When I try to select a chunk of html with a hidden[display:none] movie in it [soundmanager2's swf], it gives me:
el.currentStyle is null or undefined
on ie8.
As a quick workaround I did this:
```
        var getComputedStyleProperty;
        if (typeof window.getComputedStyle != UNDEF) {
            getComputedStyleProperty = function(el, propName) {
                return getWindow(el).getComputedStyle(el, null)[propName];
            };
        } else if (typeof document.documentElement.currentStyle != UNDEF) {
            getComputedStyleProperty = function(el, propName) {
                if(el.currentStyle) {
                return el.currentStyle[propName];
            } else {
                return null;
                }
            };
```
But I am not sure if returning something else instead of null would be better?

**Comment by timdown** [comment]
Sorry to have taken so long to get to this. I will fix it in the next few days.

**Comment by timdown** [comment]
I'm struggling to replicate this. Could you give me some pointers? I'll try again tomorrow anyway.

**Comment by timdown** [comment]
I couldn't replicate it but I added a null check anyway so it shouldn't happen again.
