### ISSUE TITLE
AMD: Return API for modules as well

### ISSUE THREAD

**Issue by thomasbachem** [timdown/rangy#269]
First of all thanks for adding AMD support, Tim!

If I want to use a rangy module, e.g. selectionsaverestore, I currently need to do:

```js
define(
	[
		'rangy/rangy-core',
		'rangy/rangy-selectionsaverestore',
		'MyOtherModule'
	],
	function(rangy, rangySelectionSaveRestore, myOtherModule) {
		rangy.saveSelection();
	}
);
```

Because the `rangy/rangy-selectionsaverestore` module doesn't return rangy's API, I need to ignore its return value and require the core module as well.

If the module itself would also return the API, it would be enough to do:

```js
define(
	[
		'rangy/rangy-selectionsaverestore',
		'MyOtherModule'
	],
	function(rangySelectionSaveRestore, myOtherModule) {
		rangySelectionSaveRestore.saveSelection();
	}
);
```

Do you think we could improve rangy's AMD API?

PS: I think you should also get rid of the "rangy-" prefix before all the file names :)

**Comment by timdown** [comment]
Modules now return a reference to the main Rangy object (see #270).

Regrading file name prefixes, the files started out without prefixes but I added them ages ago for some reason I have forgotten. Now, I have no strong opinion. Barely even a weak one. I'll change it if more people ask or you can come up with a really persuasive argument :)
