### ISSUE TITLE
SVG text highlighting

### ISSUE THREAD

**Issue by parisni** [timdown/rangy#272]
Hello, 

Do you think it would be possible to highlight text in a SVG element ?
I have a SVG file loaded in the DOM. It has some text :        

```
<svg height="30" width="200"><text x="0" y="15" fill="red">I love SVG!</text></svg>
```

I have tried to manually add to the file : 

``` 
<svg height="30" width="200"><text x="0" y="15" fill="red"><tspan class="hightligh">I love SVG!</tspan></text></svg>
```
This add a color to my text. However, when I apply your "highlightSelection()" function (and modify it a little to add "tspan" instead of "span" ), I get exactly the same result in the DOM, but as a result the text disapears. It seems that the CSS does not apply the same way

Thanks for any idea

**Comment by parisni** [comment]
Well, 

I have edited your rangy-classapplier.js, replaced "createElement" with doc.createElementNS("http://www.w3.org/2000/svg"
and i am happy to say that : 
- highligting works on svg (no background color but fill color)
- serialisation works too
Then maybe I need to add something detecting  if this is svg or html document to apply createElementNs or simple createElement. To be continued

**Comment by timdown** [comment]
Have you tested in IE? I seem to remember there's an issue with `classList` and `className` (which the class applier module uses) in IE that I've had to work round in other projects involving SVG.

**Comment by parisni** [comment]
No, I have only tested on chrome ... I have to try

**Comment by nchase** [comment]
I don't know the exact issue you guys are talking around, but I thought I'd chime in with a known-issue in IE11 w/r/t `classList`:

the `classList.toggle` method is a bit incomplete in IE. It doesn't take a second argument which will force toggling on/off based on whether or not a truthy value is passed to it ([source](https://connect.microsoft.com/IE/feedback/details/878564/element-classlist-toggle-does-not-support-second-parameter)), so you have to use a combination of `classList.add` and `classList.remove` instead.

**Comment by parisni** [comment]
This actualy only works on firefox & chrome.
I am distraught.

**Comment by timdown** [comment]
@parisni It may be fixable. I'll get back to you.

**Comment by timdown** [comment]
I have it working in IE 11. The issue, which I've seen before, is that `classList` doesn't exist and `className` has another meaning for SVG elements in IE, so Rangy's `addClass`, `hasClass` and `removeClass` methods don't work. I've ported some more careful implementations of these from another project of mine and got instant success. I'll think about how to integrate this properly.

In the meantime, here is a patched class applier file:

https://gist.github.com/timdown/d9e753c61680ec566e50

**Comment by parisni** [comment]
Good news ! Even if  only works on IE11 
I will try it  on monday. 
Anyway thanks for helping

**Comment by timdown** [comment]
Works on IE 9 as well.

**Comment by parisni** [comment]
Hello Tim,

Well I have tested it a little (replaced the classapplier.js you give there https://gist.github.com/timdown/d9e753c61680ec566e50)
Some remarks with the patched version :

What works :  
- Highlight works on SVG (with elementTagName:"tspan") (I only found a IE8 computer, still waiting to test on later version)
- Highlight works on html <a></a>
- serialisation module works on svg too 

What does not work : 
- Highlight does not work on other stuff like html div h1 , and other html element. The text choosen disapears. (actually when I inspect the DOM, the span is an svgElement and not a htmlElement)
-  Removing highlight on svg does not work. Is there a solution ?

Surely I am mis-using your library
Thanks by advance

**Comment by timdown** [comment]
Have you got a demo page so I can see exactly what you're trying to do?

**Comment by timdown** [comment]
Everything works as expected for me with the latest release.

**Comment by VishalKumarMitra786** [comment]
I an facing the same issue, I have a page which contains both HTML elements as well as some Svg elements now the library is able to parse through the HTML elements but it is making the SVG Text to disappear . 

Example:
Say I have a text "Hello world" in one of the Html Element and in the SVG Text element I have a Tspan element which contains the text as "Hello Hello" , now if i Search the letter 'H' it is getting highlighted in the HTML element but it is getting disappeared in the SVG element it shows "ello ello" 

Is this Problem/Issue is solved by you or still pending? , I am using your library and its awesome but I am stuck in this ,Please help!

Thank in advance

**Comment by parisni** [comment]
as far as I remember, this problem is related to navitator. Firefox was running fine, chrome & IE was buggy. Personnaly I mooved on annotatorjs/HTML/pdf2htmlEX and gave up svg.

**Comment by VishalKumarMitra786** [comment]
In firefox also the letter is getting disappeard , so there is no solution for this ?
