### ISSUE TITLE
`undefined is not a function`

### ISSUE THREAD

**Issue by nschloe** [timdown/rangy#273]
I'm getting the error message
```
TypeError: undefined is not a function
    at Object.rangy.createModule.Highlighter.unhighlightSelection (http://localhost:8080/index.js:56099:88)
```
in <https://github.com/timdown/rangy/blob/master/src/modules/rangy-highlighter.js#L484> (rangy 1.3.0-beta).

How can I best debug this?

**Comment by timdown** [comment]
My guess is that you're passing in a native selection object obtained from `window.getSelection()` or `document.getSelection()`. Is that the case? If so, use `rangy.getSelection()` instead.

**Comment by nschloe** [comment]
I was using
```
userSelection = $window.getSelection().getRangeAt(0);
```
indeed. Changing this to
```
userSelection = rangy.getSelection();
```
fixed the problem. Thanks!
