### ISSUE TITLE
Chrome: "Discontiguous selection is not supported."

### ISSUE THREAD

**Issue by fresheneesz** [timdown/rangy#276]
On chrome 40.0.2214.111 m, when just loading the page with rangy, it gives me that error message on the console. Is that supposed to be a warning? A module shouldn't be throwing errors onto the console.

**Comment by timdown** [comment]
Which version of Rangy? I added a workaround for that a while ago. I disagree with the wisdom of Chrome's behaviour here, incidentally.

See issue #247.

**Comment by fresheneesz** [comment]
This is the latest version of rangy that's on npm - version 1.3.0-beta.1

**Comment by timdown** [comment]
I have the same version of Chrome and see no error with 1.3.0-beta.1.

**Comment by fresheneesz** [comment]
Hmm, it seems like there might be a weird interaction between rangy and [syn](https://github.com/bitovi/syn). I have a repro setup here:

http://www.btetrud.com/files/rangybug.zip

Unpack it, run node testServer.js, and load up localhost:8100 to test it. If its a bug in syn I'll write an issue there

**Comment by soluml** [comment]
I'm actually running into the issue in Chrome 41 with Rangy 1.3.a20150122.

I'm primarily using Rangy to get selections from within iframes.  However, sometimes just loading the page triggers this error in Chrome.

**Comment by timdown** [comment]
@fresheneesz, thanks for the test case. I was easily able to see the problem from that. Fortunately it was easy to fix.
