### ISSUE TITLE
storing selection objects

### ISSUE THREAD

**Issue by nschloe** [timdown/rangy#279]
I would like to store a selection objects as retrieved from `rangy.getSelection()` for later highlighting. Shallow copying
```
var mySelection = rangy.getSelection();
```
won't do to the trick, and also lodash's `clone`
```
var mySelection = _.clone(rangy.getSelection());
```
doesn't seem to work. Any hints?

**Comment by nschloe** [comment]
Probably, the [serializer module](https://code.google.com/p/rangy/wiki/SerializerModule) is what I want. The `rangy.serializeSelection(textSelection)` returns an empty string, however. Any idea what might be going wrong?

**Comment by nschloe** [comment]
Debugging this right now. It turns out that
```
textSelection.getAllRanges()
```
is empty. Investigating why that might be...

**Comment by parisni** [comment]
Hi !

I wan't exactly the same feature. I guess serializer module (you can test it http://rangy.googlecode.com/svn/trunk/demos/serializer.html) is not a good idea because it depends on the browser the client uses. 
I am interrested in a solution to store those objects too !

**Comment by parisni** [comment]
Well I have found a workaround, but maybe it won't satisfied you.
I serialize the entire DOM (with jquery) and send it to the server. Then, for each modification by users, save a new version of the document
1) first page without highlight
2) user1 adds highlight -> send to serveur (version2 with highlight )
3)  user2 connect, looks version2 ; he adds his own highlight -> send to server version3
4... etc

My case the document is an SVG,  this idea works for html too.

Here is the code
<div id="myTextUserCanHighlight">
Hey you can highlight me
</div>
```
<script type="text/javascript">
function svg(e) {
var svg = $("#myTextUserCanHighlight");
var s = new XMLSerializer();
var svgContent = s.serializeToString(svg[0]);//to send to the server with POST http Request
console.log(svgContent);
}
</script>
<a href='#export' onclick="svg(this)">export</a> ```

You store this dynamic div in database, and dynamix load it in your page. It will get the highlight of users (if they do not connect the same time on your website)

**Comment by timdown** [comment]
I've added `saveRanges()` and `restoreRanges(saved)` to selection. The object returned by `saveRanges()` just contains an array of copies of the selection's ranges and a selection direction.

**Comment by andrenarchy** [comment]
While trying to work around bug #282, I realized that the introduced methods `saveRanges()` and `restoreRanges()` do not work if the DOM has been modified between `saveRanges()` and `restoreRanges()`. This should probably be mentioned in the documentation.

**Comment by timdown** [comment]
@andrenarchy Good point. I've updated the documentation.
