### ISSUE TITLE
feature: allow user to disable alerts

### ISSUE THREAD

**Issue by RichardLitt** [timdown/rangy#280]
I've got rangy working in a browserified chrome extension. The extension is always on, and every now and then, rangy does not work in the environment. This happens every time I open a new tab from a Google search link, for instance. In such cases, it throws an alert, although I'm not using rangy at that moment and it is just alerting from the Chrome extension. 

Is there a way I can require rangy without enabling alerts? I'd rather the user never see them, or just console.log them. 

![screenshot 2015-03-04 10 25 35](https://cloud.githubusercontent.com/assets/910753/6490226/9efec400-c259-11e4-8bd1-26f9c8a23709.png)

**Comment by timdown** [comment]
You can disable alerts by setting `rangy.config.alertOnFail = false`. The failure message will then go to `console.log` instead.

**Comment by RichardLitt** [comment]
Thanks. Works.

**Comment by RichardLitt** [comment]
I may have spoken too soon. Even with this:

```js
var rangy = require('rangy')
rangy.config.alertOnFail = false
```
I still can see alerts. Is there a way we can pass the config directly into the module?

**Comment by timdown** [comment]
I've set the default for that option to `false`.

**Comment by RichardLitt** [comment]
Thanks @timdown. Can you bump the version for npm?

**Comment by timdown** [comment]
I'm planning to do another beta release at the weekend once I've fixed a few bugs. Can you wait until then?

**Comment by RichardLitt** [comment]
Not a problem. Thanks. 



—
