### ISSUE TITLE
ClassApplier module alter contents of style tag

### ISSUE THREAD

**Issue by JustBlackBird** [timdown/rangy#281]
As I see a combination of `Highlighter` module and `ClassApplier` module alters content of `style` tag, but this tag definitely must not be touched. Here is the test case:
```html
<html>
  <head>
    <title></title>
    <script type="text/javascript" src="rangy/lib/rangy-core.js"></script>
    <script type="text/javascript" src="rangy/lib/rangy-classapplier.js"></script>
    <script type="text/javascript" src="rangy/lib/rangy-highlighter.js"></script>
    <script type="text/javascript">
      var highlighter;

      window.onload = function() {
        rangy.init();
        highlighter = rangy.createHighlighter();
        highlighter.addClassApplier(rangy.createClassApplier('highlight'));
      }

      function highlight() {
        highlighter.highlightSelection('highlight');
        rangy.getSelection().removeAllRanges();
      }

      function removeHighlights() {
        highlighter.removeAllHighlights();
      }

      function showStyle() {
        alert(document.querySelector('style').innerHTML);
      }
    </script>
  </head>
  <body>
    <div>The first div</div>
    <style>.highlight {background-color: lime;}</style>
    <div>The second div</div>
    <div>The third div</div>
    <button onclick="highlight()">Highlight</button>
    <button onclick="removeHighlights()">Remove highlights</button>
    <button onclick="showStyle()">Show style</button>
  </body>
</html>

```
How to reproduce:

1. Click on "*Show style*" button right after the page is loaded. You'll get `.highlight {background-color: lime;}`.

2. Select contents of the last div (ex. `third`), click on "*Highlight*" button and then click on "*Show style*". You'll get `.highlight {background-color: lime;}` and it's correct behavior too. Also the contents will be highlighted with lime color.

3. Select something including contents of the first and second div (ex. `first div The second`), click on "*Highlight*". The contents will not be highlighted although a wrapper span tag will be created. Moreover, if you click on "*Show style*" FF alerts nothing while IE alerts `<span class="highlight">.highlight {background-color: lime;}</span>` which means that the contents of style tag are affected too.

4. Click on "*Remove highlights*" button. After that you can start from the first point.

I'm using Rangy 1.3.0-beta.1 and test the behavior in FF36 and IE11.

------
**UPD**: The `ClassApplier` also alters contents of `script` tags in the same conditions.

**Comment by JustBlackBird** [comment]
Also `ClassApplier` adds span wrapper to contents of `textarea` but, as I believe, it should not do so.

**Comment by timdown** [comment]
Good point. I'll fix this. Thanks for the clear test case.

**Comment by timdown** [comment]
Fixed. Elements that may contain text that are now ignored: `script`, `style`, `iframe`, `textarea` and `select`.

**Comment by JustBlackBird** [comment]
The problem is fixed now. Thank you @timdown
