### ISSUE TITLE
splitBoundaries() + normalizeBoundaries() changes selection

### ISSUE THREAD

**Issue by andrenarchy** [timdown/rangy#282]
Consider the following snippet:
```javascript
var range = rangy.deserializeRange(serializedRange, rootNode);
range.splitBoundaries();
// work with splitted nodes (but don't change the DOM)
range.normalizeBoundaries();
```
If  `splitBoundaries()` and `normalizeBoundaries()` are used like this and `range` intersects with the current selection (or it *is* the current selection), then the current selection is modified (here with Chrome).

The workaround mentioned in #93 does not work anymore (probably because the range object in the workaround seems to be modified). Maybe this is related to #279.

Any ideas?

**Comment by timdown** [comment]
`splitBoundaries()` and `normalizeBoundaries()` do change the DOM so if the range in question overlaps with the selection then it can affect it. Rangy provides several ways to save and restore a selection; the most reliable here would probably by the [selection save and restore module](https://github.com/timdown/rangy/wiki/Selection-Save-Restore-Module), provided the extra marker elements that it adds temporarily don't get in your way.

**Comment by andrenarchy** [comment]
Unfortunately, I cannot allow rangy to manipulate the DOM in my application (because I temporarily change it myself). As mentioned in #279, I tried to use `selection.saveRanges()` and `selection.restoreRanges()` but they don't work when the DOM is manipulated. 

As a workaround I currently use:
```
var currentSelection = rangy.serializeSelection(rangy.getSelection(), true);

// call splitBoundaries(), do some work and then call normalizeBoundaries()

if (currentSelection) {
  rangy.deserializeSelection(currentSelection);
}
```

**Comment by timdown** [comment]
That's probably the best workaround if you're sure the structure of the DOM will be identical before and after your changes.

**Comment by andrenarchy** [comment]
OK, thanks! (the DOM is identical before/after)
