### ISSUE TITLE
normalizeBoundaries and Chrome don't play well together

### ISSUE THREAD

**Issue by DeadMG** [timdown/rangy#293]
When selecting text in Chrome, the browser makes the selection always be at the end of a text node, even if it should be at the start of the next text node. The browser splits a text node half-way when you make a selection, and then sets the range at the end of the first of the pair. When Rangy splits a boundary, it sets the range at the start of the second of the pair. 

When NormalizeBoundaries is called again then because the range is not at the start of a text node, Rangy won't normalize the boundaries again.

**Comment by timdown** [comment]
I'm not quite sure what you mean. Chrome doesn't break up text nodes when the user makes a selection. Is there some other step after making a selection that you haven't mentioned?

**Comment by DeadMG** [comment]
Not one that I made, but it's a large codebase, so it could be someone else doing the splitting.

In any case, the fundamental point that normalizeBoundaries won't normalize the boundaries if the boundary point is described the wrong way is still valid.

**Comment by timdown** [comment]
In my tests, `normalizeBoundaries()` works perfectly for all cases I could think of when a range boundary is between two adjacent text nodes. What case is failing for you?

**Comment by DeadMG** [comment]
Give me a few days and I will post a fiddle case, but if you look at domrange.js:1136, you will see that if the start node is a character node, the merge function is only called if it's at the start of that character node. It won't try to merge if the start is at the end of that character node.

**Comment by timdown** [comment]
Got it. Thanks. Fixed now.
