### ISSUE TITLE
saveSelection does not insert the span into iframe body

### ISSUE THREAD

**Issue by SlightlyCyborg** [timdown/rangy#295]
This is the savedSel object when at breakpoint marked by my commented code
 Object { rangeInfos=[0], restored=false, win=undefined}

![screen shot 2015-03-27 at 4 59 45 pm](https://cloud.githubusercontent.com/assets/1966377/6876933/bfeb2ed2-d4a2-11e4-967a-fc809b28b3ca.png)

Meta: Code pasting was messing up my code for some reason

**Comment by timdown** [comment]
I think the issue is that you're saving the selection in the main window, not the iframe. Pass in the iframe and I think you'll be fine:

```
var savedSel = rangy.saveSelection(iframe);
```

You'll need to have a reference to the iframe element but you can store that  with `var iframe = this;` outside the `setTimeout` call.

**Comment by SlightlyCyborg** [comment]
That worked. I actually had to set 
<pre><code> 
var iframes = []; 
//for each iframe using jquery
iframes.push($(this).get(0));
 </code></pre> 

and then pass one of the elements of that array into the function since the iframe variable would get overwritten before the callback was executed. Other than that I had no problems.

 Thankyou!!!

**Comment by SlightlyCyborg** [comment]
Heres a coffee on me @timdown @changetip for the help!

**Comment by changetip** [comment]
Hi @timdown, @SlightlyCyborg sent you a Bitcoin tip worth a coffee (5,895 bits/$1.51), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/687742)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
