### ISSUE TITLE
ExtractContents handles break tags incorrectly

### ISSUE THREAD

**Issue by dok** [timdown/rangy#298]
This issue occurs in chrome v41 in Mac OS in  rangy version: 1.3.0-beta.2.

The issue appears when a break tag is consumed by extract contents when it is selected.

Here is what the DOM looks like before extractContents:
![screen shot 2015-04-07 at 10 42 44 pm](https://cloud.githubusercontent.com/assets/1214868/7039498/aff9b344-dd77-11e4-9f2d-092a4849c1fb.png)

Here is the after-effects:
![screen shot 2015-04-07 at 10 43 12 pm](https://cloud.githubusercontent.com/assets/1214868/7039502/b71b894a-dd77-11e4-8bac-8bb767e60d14.png)

**Comment by dok** [comment]
It seems like it's just a native range bug.. Should rangy try and sanitize this (honest question)?

**Comment by timdown** [comment]
If the issue is the that `<br>` in the first screengrab becomes `<br></br>` in the second, then that's not a bug at all, just a quirk of Chrome's how dev tools represent the DOM. Check the `childNodes` property of the fragment to be sure.

**Comment by dok** [comment]
Thanks for the response. This is really bad because the <br></br> is interpreted by contenteditable as double break tags after refreshing.. Do you know of any way to mitigate the issue?

**Comment by timdown** [comment]
I may have been too hasty, but I need a few more details. What are you doing with this fragment and what do you mean by refreshing? A list of steps to reproduce the issue would be ideal.

**Comment by dok** [comment]
My original intention was to override the shift+enter behavior in contenteditable as it turns classes into computed styles, which is not ideal. When something is selected and the user does the shift+enter press, it would extract the contents, create a br tag and push it into the right position.

Now that I look into this issue, I don't think it's a rangy issue at all.. Like you said, it is related to how the browser interprets a break tag. Here are some examples. 

The first scenario is the aftermath when of the non-self closing break tags are appended [link](http://jsfiddle.net/L97yv5be/).

The scenario where the br tags are turning into non-self-closing ones are much harder to reproduce... But in point where they are turning into the irregular br tags, I am simply doing an [dom node].appendChild([br tag]) to insert them into the contenteditable div..

**Comment by dok** [comment]
I found the issue. We were injecting text nodes inside break tags somewhere in the process -____-;

False alarm. Thanks for your speedy responses.
