### ISSUE TITLE
Bower dependency management fails due to missing bower.json

### ISSUE THREAD

**Issue by bbottema** [timdown/rangy#300]
Rangy not being picked up by dependency injectors, because they have no way of knowing what the _main_ file is for rangy. package.json has the main property, but these injectors often look to a bower config for the same property. I couldn't find such a config in this repository.

As a result, rangy is missing among dependencies managed by for example [grunt wiredep](https://github.com/stephenplusplus/grunt-wiredep). Also see https://github.com/fraywing/textAngular/issues/144#issuecomment-91470030 for an example of this when depending on [textAngular](https://github.com/fraywing/textAngular).

```html
<!-- bower:js -->
<script src="bower/textAngular/src/textAngular.js"></script>
<script src="bower/textAngular/src/textAngular-sanitize.js"></script>
<script src="bower/textAngular/src/textAngularSetup.js"></script>
... bower/textAngular/dist/textAngular-rangy.min.js missing ...
<!-- endbower -->
```

**Comment by timdown** [comment]
I need to look into this, but I'm sure you're right, so why have you closed it?

**Comment by bbottema** [comment]
Because the various rangy files were included properly as dependencies to https://github.com/fraywing/textAngular. I didn't look carefully enough.

The confusion was because textAngular was talking about a provided range.min packaged with textAngular, which was not picked up by wiredep. The normal rangy dependencies however were and it worked fine.

**Comment by timdown** [comment]
Great.
