### ISSUE TITLE
selection.text() contains extra whitespace

### ISSUE THREAD

**Issue by domehead100** [timdown/rangy#304]
I'm dealing with HTML that is generated via an RTF -> HTML conversion.  That conversion makes use of spans for formatting text runs from the RTF (which generates a lot of spans!).

The HTML down below represents the text "female presents to the ED with a Chief Complaint of Shoulder Pain".

When I select this text in the browser (Chrome), and do rangy.getSelection().text(), I end up with an extra space in the text where new spans start.  So, I end up with two spaces between the words "female" and "presents" and two spaces between "Complaint of" and "Shoulder".

From some experimentation, I can use some regexes to get the HTML from the selection and remove all of the tags and whitespace between tags, and this gets me the correct text:  `rangy.getSelection().toHtml().replace(/>\s+</gm, "><").replace(/<[^>]*>/gm, "");`

but I was wondering if there's something I'm missing here or if this is a known behavior of rangy?

``` html
<span style="font-family:Arial; font-size:11pt; font-weight:normal; text-decoration:none" data-point-size="11">female</span>
        <span style="font-family:Arial; font-size:11pt; font-weight:normal; text-decoration:none" data-point-size="11"> presents to the ED with a Chief Complaint of </span>
        <span style="font-family:Arial; font-size:11pt; font-weight:normal; text-decoration:none" data-point-size="11">Shoulder Pain</span>
```

**Comment by timdown** [comment]
Definitely a bug. I'm working on it now.

**Comment by timdown** [comment]
Fixed. Will be in next release.
