### ISSUE TITLE
highlighter doesn't use highlighter.doc as default selection when specified

### ISSUE THREAD

**Issue by frafra** [timdown/rangy#305]
Hi,
I'm using Firefox 37 x86_64 on Fedora 22 and Rangy 1.3 beta (rev 133c7c6f3f).
highlighter.serialize and removeAllHighlights work as expected even with `<iframe>` elements, while highlight.highlighSelection doesn't (nothing seems to happen).

Demo (live): https://about.frafra.eu/rangy-iframe-highlighter-bug/
Demo (code): https://github.com/frafra/rangy-iframe-highlighter-bug

**Comment by frafra** [comment]
The problem is caused by the fact that `highlightSelection` (and other functions) calls `api.getSelection()` instead of `api.getSelection(this.doc)`. I think that if an highlighter is created on a custom document, this document should be used as default selection.

Workaround (example):
```
var customSelection = rangy.getSelection(highlighter.doc)};

highlighter.highlightSelection(style, {selection:customSelection});
highlighter.unhighlightSelection(customSelection)
/* etc. */
```

**Comment by timdown** [comment]
Thank you, this is very helpful. I've made a fix and it will be in the next version,
