### ISSUE TITLE
Highlighter highlightSelection() refreshes existing selection

### ISSUE THREAD

**Issue by mmariano** [timdown/rangy#308]
The highlighter module `highlightSelection()` allows you to pass in a selection object using the options. However the `createOptions()` code will always call `api.getSelection()` to get a default even if you pass in a selection. This causes the selection object you passed in to get refreshed. So if anything has changed since passing in the original selection object it will then get updated. In my use case the selection object that was passed in was a snapshot of an action the user performed and it should not be refreshed.

Can you please avoid calling `api.getSelection()` if someone passes in an existing selection object? 

Also is there something I can do to lock a selection so another selection can't modify it?

https://github.com/timdown/rangy/blob/master/src/modules/rangy-highlighter.js#L446

**Comment by timdown** [comment]
That's a good point. I've added a fix. The lib directory has newly-built files.

As for your question, the selection in 1.3 has [`saveRanges()`](https://github.com/timdown/rangy/wiki/Rangy-Selection#saveranges) and [`restoreRanges()`](https://github.com/timdown/rangy/wiki/Rangy-Selection#restorerangessaved) which allow you to snapshot the selection.
