### ISSUE TITLE
Loop all words to apply a class

### ISSUE THREAD

**Issue by Solaner** [timdown/rangy#309]
I'm looking for a clean way to loop through the words of an element, where I wanted to apply individual CSS Classes to the words.
I tried to adapt the code from https://github.com/timdown/rangy/issues/130:
```javascript
function printWords() {
  var it = rangy.createWordIterator(document.body, 0, 'forward');
  while ( (word = it.next()) ) {
    if (word.isWord) {
      console.log(word.toString());
    }
  }
}

window.onload = function() {
  rangy.init();
  printWords();
};
```

I tried to insert my Class Applier code (with `applyToRange` or `applyToSelection`), but everything has failed.
Meanwhile I think this is, because it's not possible to create a range or a selection with the token `word` or the iterator `it`.
Is there a solution to do this with the word iterator or is there a solution with a different iterator?

**Comment by Solaner** [comment]
The above shown function *printWords* prints every word of a page.
Therefore, it seems to me a good starting point for doing what I want.
I have tried other ways like the following:
```javascript
function printWords() {
	var range = rangy.createRange();
	range.collapseBefore(document.body);
	do {
		range.expand("word", { wordOptions: { includeTrailingSpace: false }});
		console.log(range.toString());
	}
	while (range.move("word", 1, { wordOptions: { includeTrailingSpace: true }}));
}
```
However, this version omits the first word of every phrase.

**Comment by timdown** [comment]
The problem with `createWordIterator` is that it relies on the DOM staying the same between calls to `next()`. You could use it to store a list of character ranges and iterate over this list, creating a range and applying a class to it for each character range, but Rangy doesn't make this easy because the object returned by `next()` does not contain a convenient range representing the word.

Your second example seems to work for me: http://jsbin.com/liqewoxowa/2/edit

**Comment by Solaner** [comment]
Thank you very much for your reply and for the jsbin!
In my previous comment I mentioned, that it omits the first word of every *phrase* (I meant *sentence* – sorry for my bad English). 
I cloned your jsbin to show what I meant: http://jsbin.com/yuxegomuva/1/
It seems that the punctuation marks cause the problem.

**Comment by birkanu** [comment]
@timdown, can you elaborate more on how to do it with the `createWordIterator` way? That works best for my purpose, but as @Solaner mentioned, I can't apply a class on words.

**Comment by writer0713** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

writer0713@naver.com 님께 보내신 메일 <Re: [rangy] Loop all words to apply a class (#309)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
