### ISSUE TITLE
createClassApplier creates multiple nested elements.

### ISSUE THREAD

**Issue by brandondurham** [timdown/rangy#316]
This could very well be user error, but here is the scenario. I have the following function:
```javascript
var theRangyClass = rangy.createClassApplier(font.filename, {
	applyToEditableOnly: true,
	normalize: true,
	tagNames: ['span', 'p'],
	elementProperties: {
		style: {
			fontFamily: font.filename,
			fontWeight: 100 || font.weight,
			fontSize: 42,
			fontStyle: font.style
		}
	}
});
theRangyClass.toggleSelection();
```

It works wonderfully on the first application. I select some text and run the function and it wraps the text accordingly:

```html
<span class="Historical-FellTypeRoman" style="font-family: Historical-FellTypeRoman; font-weight: 100; font-style: normal;">I am Basil Elton, keeper of the North Point light that my father and grandfather kept before me.</span>
```

But if I leave the text selected and run the function again with different parameters it just adds a nested span tag with the same attributes:

```html
<span class="Historical-FellTypeRoman" style="font-family: Historical-FellTypeRoman; font-weight: 100; font-style: normal;">
	<span class="Historical-FellTypeItalic" style="font-family: Historical-FellTypeItalic; font-weight: 100; font-style: italic;">I am Basil Elton, keeper of the North Point light that my father and grandfather kept before me.</span>
</span>
```

Is there a way to instruct Rangy to reuse the current element (in my case, a `<span>`) if all of its contents are currently selected?

**Comment by timdown** [comment]
A Rangy class applier will reuse an existing element, so long as:

* the `useExistingElements` option is `true` (which it is by default)
* the element tag name is in the list of allowed tag names
* the element's attributes match all the attributes in the `elementAttributes` option
* the element's properties match all the attributes in the `elementProperties` option

It's the final point that is the problem here, since the style properties you're setting differ between the two class appliers. If possible, I'd suggest putting all those style properties in the class, but I imagine there's a good reason you're not already doing that.

**Comment by brandondurham** [comment]
Yeah, this is part of a Webpack/React app. I may be able to create classes with styles on-the-fly, which is suppose would solve this problem? In that case it sounds like it'll just switch out the className on the span. I'll give that a shot and report back.

**Comment by brandondurham** [comment]
Alrighty, using the smart-css package to create classes on-the-fly and it's working wonderfully, with one exception: It's adding the classes instead of replacing them.

```
<span class="Gotham-Bold0 Gotham-Thin1 Gotham-LightItalic2">Basil Elton</span>
```

I suspect I’ll need to clear out the previous class myself?

**Comment by brandondurham** [comment]
I was able to solve for this by doing the following:

```javascript
var theRangyClass = null;

// If theRangyClass exists, clear it
if (theRangyClass) { theRangyClass.undoToSelection(); }

// Create the CSS class and inline styles based on the font
// parameters passed in from the JSON
theRangyClass = rangy.createClassApplier(css.getClass(font.filename), {
	applyToEditableOnly: true,
	tagNames: ['span']
});

// Apply the class and styles to the selected text
theRangyClass.applyToSelection();
```
