### ISSUE TITLE
DOMException: INDEX_SIZE_ERR in IE, from rangy-core.getSelection function

### ISSUE THREAD

**Issue by mak962753** [timdown/rangy#318]
This error is specific to IE only (I use the latest version), it is raised from rangy-core getSelection function, when cursor is on textarea or in text input.

Can be reproduced on http://rangy.googlecode.com/svn/trunk/demos/core.html
Put cursor into Selection/Range HTML textarea and click the Get Selection Text button.

**Comment by timdown** [comment]
That's a bug in the demo but not in Rangy. If the selection's `rangeCount` count is 0, which it is in IE when a text input or textarea has focus, calling `getRangeAt(0)` on the selection will throw this error by design.

I've updated the demo to fix this. I'll also add a note to the documentation.
