### ISSUE TITLE
setting cursor at selection start

### ISSUE THREAD

**Issue by kakabomba** [timdown/rangy#320]
Hello,  I need replace DOM elements and restore selection after replacement.

Function setStartAndEnd fails when end is before start. This is expected behavior?

example: http://jsfiddle.net/1039y6nq/3/

Thanks

**Comment by timdown** [comment]
Yes, this is expected. Unlike a selection, a range doesn't have a direction. `setStartAndEnd` doesn't check whether the end point is before the start point and just goes ahead and sets the start and then end with whatever you've given it.

Rangy has various options for saving and restoring a selection and they all preserve direction in browsers that support it (i.e. everything except Internet Explorer). You can also set a backwards selection with `selection.setStartAndEnd(range, "backwards")`.
