### ISSUE TITLE
Highlighter module demo broken?

### ISSUE THREAD

**Issue by Ghazgkull** [timdown/rangy#325]
I'm just checking out Rangy for the first time because I want to highlight a user's selected text to word boundaries. I'm looking at the [highlighter module demo](http://rangy.googlecode.com/svn/trunk/demos/highlighter.html), because it sounds like what I need.

I select text and press the various buttons, but nothing ever happens. I expected that the text I selected would somehow show as highlighted. Am I misunderstanding or is the demo broken?

**Comment by izhan** [comment]
Ran into this issue a week ago.  It was due to missing files in the script src tags.  Revisiting the page again...I believe this issue has been fixed?

**Comment by timdown** [comment]
Yes. I am intending to move the demos to GitHub pages but in the meantime I patched up the existing ones. See also #329.
