### ISSUE TITLE
Find demo page appears broken

### ISSUE THREAD

**Issue by wotzisname** [timdown/rangy#329]
![image](https://cloud.githubusercontent.com/assets/5259000/9324521/2e1785bc-4583-11e5-8a41-7e9bfe52ea91.png)

**Comment by nchase** [comment]
All of the rangy stuff on Google Code is outdated as far as I know – rangy is now hosted here on Github. 

You can run the demos by cloning the repository here and then opening the demo in your browser.

**Comment by timdown** [comment]
I am intending to put the demos on GitHub pages (although I'm open to other suggestions) soon. In the meantime, I have been trying to maintain the demos on Google Code, so I'll fix this.

**Comment by timdown** [comment]
Temporary fix applied.
