### ISSUE TITLE
IE11, Module 'WrappedSelection' failed to load: Unspecified error.

### ISSUE THREAD

**Issue by Zergus** [timdown/rangy#335]
Initing WrappedSelection falls down during 'Test whether the native selection is capable of supporting multiple ranges.'. Reason is sel.addRange(r1) that acquires error when executed in IE11. Debug showed that error occurred only after setting:
```javascript
r1.setStart(textNode, 0);
r2.setEnd(textNode, 3);
r2.setStart(textNode, 2);
```
I wonder what is wrong here.

**Comment by timdown** [comment]
I'm currently on holiday. I'll get to this hopefully next weekend. In the meantime, this doesn't happen for me in the simple set-up in IE11 that the unit tests use; could you give me a few details on how to replicate this?

**Comment by Zergus** [comment]
I've just initiated textangular, that requires rangy.js in IE11. While it was initializing the error  'WrappedSelection' failed to load: Unspecified error was dropped to console. But I all I need to reproduce this problem is to init rangy-core.js in IE11 and watch console for that error.

**Comment by simonefalcini** [comment]
Same problem here.. any news?

**Comment by Zergus** [comment]
Currently I've commented my strokes and it was like solution. I guess when I will have some time I will create pull req. when investigate hella core of IE :D

**Comment by simonefalcini** [comment]
@Zergus What do you mean? I get the same problem on IE11 (www.swite.com) 
Do you suggest commenting lines 
```javascript
r1.setStart(textNode, 0);
r2.setEnd(textNode, 3);
r2.setStart(textNode, 2);
```
in rangy-core.js ?

**Comment by devmark** [comment]
get same problem . i also comment this three line for now. 
IE only get this problem.

**Comment by Zergus** [comment]
@simonefalcini yup. They should be reviewed by @timdown

**Comment by Pudge601** [comment]
I've just encountered this same problem in IE11, what was the resolution to this? Do we just have to comment out the lines?

**Comment by shekhardesigner** [comment]
Any updates on this issue guys?

I tried commenting those three lines in rangy-core.js but no luck. This is what I get in IE11. Tried including the core-rangy unminified version as well, didn't work.

![image](https://cloud.githubusercontent.com/assets/3298585/10205575/9a439504-67df-11e5-8f5f-de7f756a0916.png)
![image](https://cloud.githubusercontent.com/assets/3298585/10205582/a23f813c-67df-11e5-8035-891bdbca63f8.png)

**Comment by razvanc92** [comment]
Did anyone solve this?

**Comment by davepilbeam** [comment]
I am lazyloading Rangy + Medium.js into CMS
Today IE11 gives me: "required module 'WrappedSelection' not supported" - but was working last week...
Tracing back I see: "Module 'WrappedSelection' failed to load: Could not complete the operation due to error 800a025e"
This error GOES AWAY for me when adding delay before calling function after Rangy + Medium.js loaded

**Comment by d3l33t** [comment]
created an issue on textAngular https://github.com/fraywing/textAngular/issues/932

**Comment by peter-mw** [comment]
same problem

**Comment by thhan** [comment]
The bug is in rangy-core.js:2967-2972. The variable r2 is empty and IE9 will throw an exception in line 2970. I hope i can help to solved this Issue.

**Comment by jeremy-kothe** [comment]
Still getting this on IE11.
