### ISSUE TITLE
Using with angular 4

### ISSUE THREAD

**Issue by RamyEl-basyouni** [timdown/rangy#434]
guys, we are trying to use rangy with angular 4 core and systemJs transpiler, but we faced lots of challenges:
-First: i installed the lib with npm install rangy
-Second: i have added the core-js to systemJs bundler    'rangy': 'node_modules/:rangy/lib/rangy-core.js'
-Third: i have installed necessary typings 
- Finally: when acquiring the library:
 rangy.getSelection().saveCharacterRanges(this.currentElement) 
 always getting cannot read undefined function saveCharacterRanges

**Comment by Greatshock** [comment]
Have you solved the issue?

**Comment by RamyEl-basyouni** [comment]
Yes it was systemJs acquiring issue, any way we migrate to webpack instead of ugly systemJs support 😊

**Comment by Greatshock** [comment]
@RamyEl-basyouni How to properly import Rangy in Angular 7 app?

**Comment by joistick11** [comment]
Sorry for the late response,
Just install rangy using npm and then import to your component:
`import * as rangy from 'rangy'`

Now you can use `rangy` variable

**Comment by RamyEl-basyouni** [comment]
@Greatshock as mentioned above

**Comment by dmytro-feld** [comment]
Hey @joistick11 @RamyEl-basyouni
Do you have any thoughts on how to use not only `core` of `rangy` but other stuff as `rangy-highlighter` or `rangy-classapplier` with `Angular`?

`import * as rangy from 'rangy'` or `import rangy from 'rangy'` (doesn't matter) - open the door only to core methods and properties. But unfortunately it's impossible to use i.e. `rangy.createClassApplier` method.

Thanks in advance for your tips!

**Comment by pedroborges** [comment]
> But unfortunately it's impossible to use i.e. rangy.createClassApplier method.

I'm maintaining an old project had the same issue today. This is how I got it working:

```js
import rangy from 'rangy/lib/rangy-core';
import 'rangy/lib/rangy-classapplier';
import 'rangy/lib/rangy-textrange';
```

Then you can use `rangy.createClassApplier` and `rangy.getSelection().saveCharacterRanges`.
