### ISSUE TITLE
rangy already defined

### ISSUE THREAD

**Issue by timdown** [timdown/rangy#51]
_From [Peta...@gmail.com](https://code.google.com/u/103447209304963985343/) on June 07, 2011 12:56:56_

Can you add a feature like jQuery's noConflict, where if rangy is already defined, we can use another name?

Or for example use 2 different versions of rangy on 1 page

_Original issue: http://code.google.com/p/rangy/issues/detail?id=51_

**Comment by Ghazgkull** [comment]
Sorry to be commenting on an ancient issue, but I came across this post while searching for a noConflict() function in Rangy. It looks like there was a code snippet in the message 2 posts up, but now it's gone.

Is there a way to load Rangy but restore any previous global rangy variable (ala jQuery.noConflict())?
